# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c0196230-58f5-4d49-b8c7-5e12c359ca58";
      fsType = "ext4";
    };

  fileSystems."/mnt/backUpDrive" =
    { device = "/dev/disk/by-uuid/c7985efa-dede-4b33-ac98-ea4382357f47";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5A55-6D91";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/gamingDrive2TB" =
    { device = "/dev/disk/by-uuid/7da7f55d-6957-474e-a1f3-6dd4427963c7";
      fsType = "ext4";
    };

  fileSystems."/mnt/bulkStorage8TB" =
    { device = "/dev/disk/by-uuid/0526e5eb-38a7-4b33-b4fc-80c0cb31fa09";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/b12d046c-8950-4668-8628-c252a0b09134"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
